from abc import ABC, abstractmethod
from dataclasses import dataclass
from pathlib import Path

from jinja2 import Environment

from .completion import CompletionCommand


@dataclass
class BuildEnvInfo:
    """
    BuildEnv information holding object, used to give some context to extensions.
    """

    venv_bin: Path | None = None
    """Path to the virtual environment binary directory (i.e. the one with all installed scripts and executables)"""

    project_root: Path | None = None
    """Path to the project root directory, if any (None otherwise)"""


class BuildEnvRenderer(ABC):
    """
    Rendering interface for buildenv extensions
    """

    @abstractmethod
    def render(self, environment: Environment, template: str, executable: bool = False, keywords: dict[str, str] | None = None):  # pragma: no cover
        """
        Render extension activation script from template

        :param environment: Jinja2 environment to use for rendering
        :param template: Template file to render (relative to provided environment)
        :param executable: States if target file as to be set as executable
        :param keyword: Map of keywords provided to template
        """
        pass


class BuildEnvEntryPoint:
    """
    Base class for **buildenv** entry points, to be contributed through "buildenv_entry_point" entry point

    :param info: BuildEnvInfo object holding information about the build environment
    """

    def __init__(self, info: BuildEnvInfo):
        self.info = info
        pass


class BuildEnvExtension(BuildEnvEntryPoint):
    """
    Base class for **buildenv** extensions, to be contributed through "buildenv_init" entry point

    :param info: BuildEnvInfo object holding information about the build environment
    """

    def init(self, force: bool) -> None:  # pragma: no cover
        """
        Method called by buildenv backend when initializing environment.

        The extension is supposed to perform some build logic initialization (once for all). This method will always be called by buildenv;
        the extension must decide by itself if it needs to perform some action or not.

        The self.info attribute can be used to access to buildenv information.

        :param force: Tells the extension if the **--force** argument was used on the **buildenv init** command line.
        """
        raise NotImplementedError("Extension must implement init method")

    def get_completion_commands(self) -> list[CompletionCommand]:
        """
        Method called by buildenv backend to get the list of commands to be completed.

        The extension can use this method to provide its own completion commands.

        :return: List of commands to be completed
        """

        # Default implementation: no command to be completed
        return []

    def generate_activation_scripts(self, renderer: BuildEnvRenderer):  # NOQA: B027
        """
        Method called by buildenv backend when generating activation scripts.

        The extension can use this method to generate its own activation scripts in the provided temporary directory.
        The default implementation does nothing.

        :param renderer: Rendering interface to use for generating activation scripts
        """

        # Default implementation: do nothing
        pass


class BuildEnvProjectTemplate(BuildEnvEntryPoint):
    """
    Base class for **buildenv** project templates, to be contributed through "buildenv_template" entry point

    :param info: BuildEnvInfo object holding information about the build environment
    :param name: Template name, used to select the template when creating a new project; read from entry point definition on instance creation
    """

    def __init__(self, info: BuildEnvInfo, name: str):
        super().__init__(info)
        self._name = name

    @property
    def name(self) -> str:
        """
        Template name, used to select the template when creating a new project
        """
        return self._name

    @property
    def description(self) -> str:
        """
        Template description, used to describe the template to users when creating a new project
        """
        return ""

    @property
    def preferred_backend(self) -> str:
        """
        Preferred buildenv backend for this template; will be used by default (instead of detected one) on buildenv install if this template is selected,
        but can be overridden by user on command line.
        """
        return "uvx"

    @property
    def generated_files(self) -> set[Path]:
        """
        List of paths to the files generated by this template, relative to project root.
        """
        return set()

    def generate_project_files(self, renderer: BuildEnvRenderer, packages: list[str]) -> None:  # pragma: no cover
        """
        Method called by buildenv backend when generating project files for a new project.

        The extension is supposed to generate all the files needed for the project, using the provided renderer.

        :param renderer: Rendering interface to use for generating project files
        :param packages: additional packages to be added to the project
        """

        raise NotImplementedError("Project template must implement generate_project_files method")
